ignores = [
    "http://10.89.74.54/NS.SSO.LDAP/LDAPAuthen.asmx",
    "https://crm-dev1.tac.co.th",
    "https://adfs.dtac.co.th/adfs/oauth2",
    "https://sculptor1.tac.co.th:7402/QueryCustomerPrivilege",
    "http://10.89.111.65:7382/",
    "http://10.89.111.36:7782/",
    "http://10.89.111.17:7382/",
    "http://10.89.111.46:7882/",
    "https://gliese1dtac-blqrysb.tac.co.th:7834/",
    "https://gliese1-blqrysb.tac.co.th:7832/",
    "https://gliese1dtac-blreqsb.tac.co.th:7854/",
    "https://gliese1-blreqsb.tac.co.th:7852/",
    "https://gliese1dtac-blltxsb.tac.co.th:7844/",
    "https://gliese1-blltxsb.tac.co.th:7842/",
    "http://www.dtac.co.th/eai/esb/ws/SVCBEQryAllUsage/QryAllUsage",
    "https://gliese1dtac-blqrysb.tac.co.th:7834/",
    "https://gliese1-blltxsb.tac.co.th:7842/",
    "https://gliese1dtac-blqrysb.tac.co.th:7834/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCPMQrySubscriber/v2_0/SVCPMQrySubscriber",
    "https://gliese1-blqrysb.tac.co.th:7832/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCPMQrySubscriber/v2_0/SVCPMQrySubscriber",
    "https://gliese1dtac-blltxsb.tac.co.th:7844/QueryCDR/CustIntrMgmt/BillEnquiry/SVCBEQryBonSumm/v2_0/SVCBEQryBonSumm",
    "https://gliese1-blltxsb.tac.co.th:7842/QueryCDR/CustIntrMgmt/BillEnquiry/SVCBEQryBonSumm/v2_0/SVCBEQryBonSumm",
    "https://gliese1dtac-blqrysb.tac.co.th:7834/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCPMQrySubscriber/v2_0/SVCPMQrySubscriber",
    "https://gliese1-blqrysb.tac.co.th:7832/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCPMQrySubscriber/v2_0/SVCPMQrySubscriber",
    "https://gliese1dtac-blqrysb.tac.co.th:7834/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCPMQrySubscriber/v2_0/SVCPMQrySubscriber",
    "https://gliese1-blqrysb.tac.co.th:7832/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCPMQrySubscriber/v2_0/SVCPMQrySubscriber",
    "http://10.89.111.17:7382/services/CardRechargeMgrService.CardRechargeMgrServicePort/",
    "http://10.89.111.46:7882/services/CardRechargeMgrService.CardRechargeMgrServicePort/",
    "http://10.89.111.17:7382/services/OrderTelMgrService.OrderTelMgrServiceSoap12Port/",
    "http://10.89.111.46:7882/services/OrderTelMgrService.OrderTelMgrServiceSoap12Port/",
    "https://gliese1dtac-blreqsb.tac.co.th:7854/OnlineUpdates/Service/CustIntrMgmt/BillReq/SVCBRVoucherRefill/v1_0/SVCBRVoucherRefill",
    "https://gliese1-blreqsb.tac.co.th:7852/OnlineUpdates/Service/CustIntrMgmt/BillReq/SVCBRVoucherRefill/v1_0/SVCBRVoucherRefill",
    "http://10.89.93.27:37214/uvc/services/UvcSoapForRecharge",
    "http://10.89.93.27:37214/uvc/services/UvcSoapForRecharge",
    "https://gliese1dtac-blltxsb.tac.co.th:7844/QueryCDR/CustIntrMgmt/BillEnquiry/SVCBEQryCostSumm/v2_0/SVCBEQryCostSumm",
    "https://gliese1-blltxsb.tac.co.th:7842/QueryCDR/CustIntrMgmt/BillEnquiry/SVCBEQryCostSumm/v2_0/SVCBEQryCostSumm",
    "https://gliese1dtac-blqrysb.tac.co.th:7834/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCBEQryInvc/v2_0/SVCBEQryInvc",
    "https://gliese1-blqrysb.tac.co.th:7832/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCBEQryInvc/v2_0/SVCBEQryInvc",
    "http://10.89.111.65:3069/services/DcDTACServices",
    "http://10.89.111.36:3069/services/DcDTACServices",
    "https://gliese1dtac-blqrysb.tac.co.th:7834/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCBEQryAcctCrdLmtSubrBgCtlInfo/v2_0/SVCBEQryAcctCrdLmtSubrBgCtlInfo",
    "https://gliese1-blqrysb.tac.co.th:7832/OnlineQuery/Service/CustIntrMgmt/BillEnquiry/SVCBEQryAcctCrdLmtSubrBgCtlInfo/v2_0/SVCBEQryAcctCrdLmtSubrBgCtlInfo",
    "http://10.89.111.65:7382/ar_cv_query/paymentDetailInit.action",
    "http://10.89.111.36:7782/ar_cv_query/paymentDetailInit.action",
    "http://10.89.111.65:7382/ar_cv_query/adjustmentDetail.action",
    "http://10.89.111.36:7782/ar_cv_query/adjustmentDetail.action",
    "http://10.89.111.65:7382/ar_cv_query/queryInvoiceDetail.action",
    "http://10.89.111.36:7782/ar_cv_query/queryInvoiceDetail.action",
    "http://10.89.111.65:7382/ar_cv_query/writeOffDetailInitMain.action",
    "http://10.89.111.36:7782/ar_cv_query/writeOffDetailInitMain.action",
    "http://10.89.111.65:3069/services/DcDTACServices",
    "http://10.89.111.36:3069/services/DcDTACServices",
    "http://10.89.111.17:7382/services/QueryMgrService.QueryMgrServicePort/",
    "http://10.89.111.46:7882/services/QueryMgrService.QueryMgrServicePort/",
    "http://10.89.111.65:7382/ar_cv_payment/paymentDTAC.action",
    "http://10.89.111.36:7782/ar_cv_payment/paymentDTAC.action",
    "http://10.89.88.150:64006/ilws/InstantLinkSOA",
    "https://emailsvc-test.dtac.co.th/einvws/EINVHistoryService",
    "https://emailsvc-test.dtac.co.th/esvapi-service/EmailVerificationService",
    "http://emailsvc-test.dtac.co.th/einvws/EINVResendService",
    "http://10.89.88.220:9080/interact/services/InteractService",
    "http://equuleus12.tac.co.th:9080/interact/services/InteractService",
    "http://10.89.94.139:10015/device-capability-service/device-capabilities?capabilityId=11000010&msisdn=",
    "http://adrastea12:7731/PartnerAPI/api/CheckPartner_By_UserID",
    "http://omropr:dtac2014@10.89.90.93",
    "http://10.89.94.2:9001/soap/services/qnpservice",
    "https://10.89.88.219:7082/cifmgateway/querycampaign",
    "http://10.89.75.30:7151/CommonDeviceInsuranceWs/QryDeviceInsuranceService",
    "http://gradius11:7429/CouponWs/SubscriberQueryCHNL",
    "https://10.89.75.30:7430/CouponOMRInqrWs/OMRInquiryService",
    "http://gradius12:7329/CouponOMRInqrWs/OMRInquiryService",
    "http://gradius12.tac.co.th:7843/ServiceBizInqrWs/InquiryCampaignService",
    "http://gradius12.tac.co.th:7843/ServiceBizInqrWs/InquiryTransactionService",
    "http://gradius11:7429/CouponOMRInqrWs/OMRInquiryService",
    "https://gradius11:7430/CouponWs/Coupon",
    "http://10.89.75.31:7801/CommonDeviceDiscountWs/InquiryDeviceDiscountService",
    "http://10.89.111.17:7382/cbs_bb_costsummarygui/initCostSummaryGuiPage.action",
    "http://10.89.111.46:7882/cbs_bb_costsummarygui/initCostSummaryGuiPage.action",
    "http://10.89.111.65:7382/ar_cv_query/queryInvoiceDetail.action",
    "http://10.89.111.36:7782/ar_cv_query/queryInvoiceDetail.action",
    "http://10.89.111.65:7382/ar_cv_query/paymentDetailInit.action",
    "http://10.89.111.36:7782/ar_cv_query/paymentDetailInit.action",
    "http://10.89.94.1:8001/MNP_CRM/login_p.htm",
    "http://regel12:7301/MNPPortingAPIService/MNPPortoutServiceWS",
    "http://regel12:7221/MNPPortingAPIService/MNPPortoutServiceWS",
    "http://regel12:7301/MNPPortingAPIService/MNPPortoutServiceWS",
    "http://regel12:7221/MNPPortingAPIService/MNPPortoutServiceWS",
    "http://regel12.tac.co.th:7311/MNPAPIServices/PinCodeMNPAPIWs/inquirypincode",
    "http://regel12.tac.co.th:7225/MNPAPIServices/PinCodeMNPAPIWs/inquirypincode",
    "http://regel12.tac.co.th:7311/MNPAPIServices/PinCodeMNPAPIWs/pincode",
    "http://regel12.tac.co.th:7225/MNPAPIServices/PinCodeMNPAPIWs/pincode",
    "https://dtacblue.acemobilecare.com/dtac#/",
    "https://www.google.com/",
    "http://10.89.111.65:7382/ar_cv_void/voidPaymentDTAC.action",
    "http://10.89.111.36:7782/ar_cv_void/voidPaymentDTAC.action",
    "https://10.89.111.17:8381/bus_cv_statemgrt/balancetoValidityMainDtacAction.action",
    "https://10.89.111.46:8781/bus_cv_statemgrt/balancetoValidityMainDtacAction.action",
    "http://10.89.111.17:7382/bus_cv_telenor/loanrequest.action",
    "http://10.89.111.46:7882/bus_cv_telenor/loanrequest.action",
    "https://10.89.94.193:6502/bme/crm/accessCRM.action",
    "https://10.89.111.17:8381/bus_cv_transferaccount/transferAccountMainDtacAction.action",
    "https://10.89.111.46:8781/bus_cv_transferaccount/transferAccountMainDtacAction.action",
    "http://10.89.111.65:7382/ar_cv_query/queryInvoiceDetail.action",
    "http://10.89.111.36:7782/ar_cv_query/queryInvoiceDetail.action",
    "http://10.89.111.65:7382/ar_cv_payment/corpPaymentInit4DTAC.action",
    "http://10.89.111.36:7782/ar_cv_payment/corpPaymentInit4DTAC.action",
    "http://10.89.111.65:7382/ar_cv_payment/multipleAccountPaymentDTAC.action",
    "http://10.89.111.36:7782/ar_cv_payment/multipleAccountPaymentDTAC.action",
    "http://10.89.111.65:3157/ar_payment_arragement_request_jsp/paymentArrangementRequestDC.action",
    "http://10.89.111.36:3057/ar_payment_arragement_request_jsp/paymentArrangementRequestDC.action",
    "http://10.89.111.65:7382/ar_cv_query/transactionMovementInit.action",
    "http://10.89.111.36:7782/ar_cv_query/transactionMovementInit.action",
    "http://10.89.111.65:7382/bus_cv_telenor/AutoPayRegistrationAction.action",
    "http://10.89.111.36:7782/bus_cv_telenor/AutoPayRegistrationAction.action",
    "http://10.89.111.17:7382/bus_cv_query/queryUsageReportAction.action",
    "http://10.89.111.46:7882/bus_cv_query/queryUsageReportAction.action",
    "http://10.89.111.17:7382/cbs_bb_sys_sms/initquerysyssms.action",
    "http://10.89.111.46:7882/cbs_bb_sys_sms/initquerysyssms.action",
    "http://10.89.111.65:7382/ar_cv_payment/corpPaymentInit4DTAC.action",
    "http://10.89.111.36:7782/ar_cv_payment/corpPaymentInit4DTAC.action",
    "http://10.89.111.17:7382/bus_cv_telenor/queryCreditManageAction.action",
    "http://10.89.111.46:7882/bus_cv_telenor/queryCreditManageAction.action",
    "http://10.89.111.17:7382/bus_cv_telenor/queryBudgetControlAndIRCreditAction.action",
    "http://10.89.111.46:7882/bus_cv_telenor/queryBudgetControlAndIRCreditAction.action",
    "http://hmnfnw51/ecmmapping/getCustomersDoc.svc/json/",
    "http://hmnfnw51/ecmconsent/GetConsentWS.svc/json/",
    "http://10.89.90.108:7001/PDFService/rest/Generate",
    "http://10.112.241.4:8011/webapp/jsp/OMRGetPriceSim.jsp",
    "http://10.112.241.4:8011/webapp/jsp/OMRSimStockCut.jsp",
    "https://devfq.ndsc.tac.co.th/DAF/Services/OMRServices.svc",
    "https://testfq.ndsc.tac.co.th/daf/services/omrservices.svc",
    "http://volans14.tac.co.th:7301/bp3/bin/PaymentGatewayKTB?param=",
    "http://10.89.75.30:7801/CommonCheckBalanceWs/CommonCheckBalanceService",
    "http://hmnfnw51/sites/eRegisPost/_vti_bin/Copy.asmx",
    "http://hmnfnw51/sites/eRegisPre/_vti_bin/Copy.asmx",
    "http://hmnfnw51/sites/eRegisPreToPost/_vti_bin/Copy.asmx",
    "http://hmnfnw51/sites/Consent/_vti_bin/copy.asmx",
    "http://hmnfnw51/sites/eRegisPost/Postpaid/",
    "http://hmnfnw51/sites/eRegisPre/Prepaid/",
    "http://hmnfnw51/sites/eRegisPreToPost/PreToPost/",
    "http://hmnfnw51/sites/Consent/ConsentDoc/",
    "http://srttsevicetest.tac.co.th/PostData/Data32Javascript",
    "http://srttsevicetest.tac.co.th/PostData/Data40Javascript",
    "http://gradius11.tac.co.th:7701/CommonJaideeHaiNet/CommonJaideeHaiNetService",
    "http://10.112.225.5/IVRService/IVRService.aspx",
    "http://srttsevicetest.tac.co.th/api/SRTTOpenItems",
    "http://srttsevicetest.tac.co.th/api/SRTTAllItems",
    "http://srttsevicetest.tac.co.th/api/GetSRTTByContactID",
    "http://10.89.75.29:7801/CashGameOnline/rest/GameInfo"
]

match = [
    "http://gradius11:7429/CouponWs/SubscriberQueryCHNL",
    "emailsvc-test.dtac.co.th:443",
    "http://emailsvc-test.dtac.co.th/einvws/EINVHistoryService"
]
